// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TMAnimeLight","status":true,"description":"在事件中显示带动画的灯光。","parameters":{"range":"0.011","defaultZ":"4","frames":"30"}},
{"name":"SZMG_fiveChessAI","status":true,"description":"","parameters":{}},
{"name":"SZMG_DDZGame","status":true,"description":"","parameters":{}},
{"name":"SZMG_onKeysDown","status":true,"description":"","parameters":{}},
{"name":"SZMG_HPBar","status":true,"description":"","parameters":{}},
{"name":"BY_NPS","status":true,"description":"v3.0.1 图片、文字、动画等自由显示","parameters":{"----基本参数设置----":"","分辨率宽度":"","resWidth":"1440","分辨率高度":"","resHeight":"900","path":"img/nps/","----图片----":"","锚点（原点）":"","Anchor":"topleft","X":"Graphics.width/2","Y":"Graphics.height/2-90","Width":"100%","Height":"100%","opacity":"1","zIndex":"10000","改变（一般用于旋转）":"","transform":"rotate(0deg)","延时":"","delay":"0","----Animation 动画----":"","Animation":"[]"}},
{"name":"AB_EnemyBook","status":true,"description":"战斗敌人图鉴系统","parameters":{"ShowCommandInBattle":"1","ShowAllBookCommandInBattle":"0","ResisterTiming":"2","ShowCurrentStatus":"0","HideUnknownStatusInSkill":"1","ShowGeneralStatusInSkill":"0","HideItemUntilGet":"0","---用語、アイコン---":"","EnemyBookCommandName":"敌人情报","EnemyBookAllCommandName":"图鉴","Achievement":"完成率","UnknownEnemy":"？？？？？？","UnknownData":"？？？","WeakElementName":"弱点属性","ResistElementName":"耐性属性","WeakStateName":"弱点状态","ResistStateName":"耐性状态","NoEffectStateName":"无效状态","DefeatNumberName":"null","UnknownDropItemIcon":"16","AddEnemySkillMessage":"%1图鉴登记了！","FailToAddEnemySkillMessage":"%1不能登在图鉴上！","MissToAddEnemySkillMessage":"%1图鉴登记失败了！","FailToCheckEnemySkillMessage":"%1的信息不明白！","---表示項目---":"","DispNo":"1","DispLv":"1","DispDefeatNumber":"0","DispHP":"1","DispMP":"0","DispATK":"1","DispDEF":"1","DispMAT":"0","DispMDF":"0","DispAGI":"1","DispLUK":"1","DispGold":"1","DispDropItems":"0","DispWeakElement":"0","DispResistElement":"0","DispWeakState":"0","DispResistState":"0","DispNoEffectState":"0","DispDescribe":"0","---属性アイコン---":"","UseElementIconInPluginParameter":"1","ElementIcons":"76 64 65 66 67 68 69 70 71"}},
{"name":"SZMG_enemyShowGold","status":true,"description":"","parameters":{}},
{"name":"SZMG_blinkSystem","status":true,"description":"","parameters":{}},
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"1440","screenHeight":"900","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"on"}}
];
